# Generated by Django 2.0.10 on 2019-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190128_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
